### ISSUE TITLE
Why in god snese you set min sdk to 33 ? I cannot even test if this work across real devices by usb cable..

### ISSUE THREAD

**Issue by renetik** [android/midi-samples#2]
I tried to lower to min sdk 30 but looks like you really use some code thad is not avaiable.. This is like super unrealistic that this is production usable anywhere in the near future.

**Comment by robertwu1** [comment]
MIDI 2.0 is only supported on Android 13 and above. Android 13 has been released for 11 months already.

**Comment by robertwu1** [comment]
See https://github.com/philburk/android-midisuite for some other samples
